# Generated by Django 4.1 on 2024-05-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.IntegerField(db_column='status', default=1),
        ),
    ]
