# Generated by Django 4.1 on 2024-05-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorperformance',
            name='date',
            field=models.DateField(db_column='created_date'),
        ),
    ]
