# Generated by Django 4.1 on 2024-05-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('poNumber', models.CharField(db_column='po_number', max_length=100, unique=True)),
                ('orderDate', models.DateTimeField(db_column='order_date')),
                ('deliveryDate', models.DateTimeField(db_column='delivery_date')),
                ('items', models.JSONField(db_column='items')),
                ('quantity', models.IntegerField(db_column='quantity', default=0)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('canceled', 'CANCELED')], db_column='status', default='pending', max_length=20)),
                ('qualityRating', models.FloatField(blank=True, db_column='quality_rating', null=True)),
                ('issueDate', models.DateTimeField(db_column='issue_date')),
                ('acknowledgmentDate', models.DateTimeField(blank=True, db_column='acknowledgment_date', null=True)),
                ('vendor', models.ForeignKey(db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor')),
            ],
        ),
    ]
