# Generated by Django 4.1 on 2024-05-01 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='deliveryDate',
            field=models.DateTimeField(db_column='delivery_date', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='issueDate',
            field=models.DateTimeField(db_column='issue_date', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='items',
            field=models.JSONField(db_column='items', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='orderDate',
            field=models.DateTimeField(db_column='order_date', default=django.utils.timezone.now),
        ),
    ]
