# Generated by Django 4.1 on 2024-05-01 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_purchaseorder_deliverydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='issueDate',
            field=models.DateTimeField(db_column='issue_date', default=django.utils.timezone.now, null=True),
        ),
    ]
