# Generated by Django 4.1 on 2024-05-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_purchaseorder_issuedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completedDate',
            field=models.DateTimeField(db_column='completed_date', null=True),
        ),
    ]
